# Created by Jekyll Writer
title: New Site
email: your-email@domain.com
description: Write an awesome description for your new site here
baseurl: /new
url: 'http://theme.jekyllwriter.com'
permalink: '/:year/:month/:day/:title/'
twitter_username: jekyllwriter
github_username: jekyllwriter
markdown: kramdown
